import type { ChartRow } from "../../utils"

export interface SeriesChartProps {
  rows: ChartRow[]
  seriesKeys: string[]
  color: string
  valueLabel: string
  height?: number
  // What a point's count actually counts — "bets" vs "txns" — shown in
  // tooltips alongside the value. Defaults to "txns" so a caller that
  // doesn't care (e.g. a future chart type without a tooltip) doesn't have
  // to pass it.
  countLabel?: string
}

// Curated brand tokens for the common case (<= 5 slices). sliceBy can return
// up to ~20 distinct values plus an "OTHER" bucket (backend caps cardinality
// at 20, see player-trends-analytics.md §3) — beyond the curated set, colors
// are generated by rotating hue at the golden angle, which keeps every new
// slice visually distinct instead of the palette repeating every 5 series.
const BASE_SERIES_COLORS = [
  "var(--chart-1)",
  "var(--chart-2)",
  "var(--chart-3)",
  "var(--chart-4)",
  "var(--chart-5)",
]

const GOLDEN_ANGLE_DEG = 137.508

// Recognizable, currency-specific colors win over the generated palette
// regardless of position — e.g. sliceBy=CURRENCY should always render SATS
// the same yellow whether it's the 1st or 4th slice, or whichever chart type
// it's viewed in.
const CURRENCY_COLOR_OVERRIDES: Record<string, string> = {
  SATS: "oklch(0.85 0.16 95)", // yellow/gold
  USDC: "oklch(0.6 0.18 250)", // blue
  USDT: "oklch(0.82 0.13 145)", // light green
}

export function getSeriesColor(key: string, index: number): string {
  const override = CURRENCY_COLOR_OVERRIDES[key.toUpperCase()]
  if (override) {
    return override
  }
  if (index < BASE_SERIES_COLORS.length) {
    return BASE_SERIES_COLORS[index]
  }
  const hue = (index * GOLDEN_ANGLE_DEG) % 360
  return `oklch(0.7 0.16 ${hue.toFixed(1)})`
}

