import { countKeyFor, type ChartRow } from "../../utils"

export interface SeriesChartProps {
  rows: ChartRow[]
  seriesKeys: string[]
  color: string
  valueLabel: string
  height?: number
}

// Curated brand tokens for the common case (<= 5 slices). sliceBy can return
// up to ~20 distinct values plus an "OTHER" bucket (backend caps cardinality
// at 20, see player-trends-analytics.md §3) — beyond the curated set, colors
// are generated by rotating hue at the golden angle, which keeps every new
// slice visually distinct instead of the palette repeating every 5 series.
const BASE_SERIES_COLORS = [
  "var(--chart-1)",
  "var(--chart-2)",
  "var(--chart-3)",
  "var(--chart-4)",
  "var(--chart-5)",
]

const GOLDEN_ANGLE_DEG = 137.508

// Recognizable, currency-specific colors win over the generated palette
// regardless of position — e.g. sliceBy=CURRENCY should always render SATS
// the same yellow whether it's the 1st or 4th slice, or whichever chart type
// it's viewed in.
const CURRENCY_COLOR_OVERRIDES: Record<string, string> = {
  SATS: "oklch(0.85 0.16 95)", // yellow/gold
  USDC: "oklch(0.6 0.18 250)", // blue
  USDT: "oklch(0.82 0.13 145)", // light green
}

export function getSeriesColor(key: string, index: number): string {
  const override = CURRENCY_COLOR_OVERRIDES[key.toUpperCase()]
  if (override) {
    return override
  }
  if (index < BASE_SERIES_COLORS.length) {
    return BASE_SERIES_COLORS[index]
  }
  const hue = (index * GOLDEN_ANGLE_DEG) % 360
  return `oklch(0.7 0.16 ${hue.toFixed(1)})`
}

export const TOOLTIP_STYLE = {
  background: "var(--popover)",
  borderColor: "var(--border)",
  borderRadius: "var(--radius-md)",
  fontSize: 12,
}

function formatNumber(value: number): string {
  return value.toLocaleString(undefined, { maximumFractionDigits: 2 })
}

// Shared by Line/Bar/Area tooltips — shows the real transaction count that
// rides along with each point (see countKeyFor) instead of just the value,
// so hovering a bucket answers "how much" and "how many" at once.
export function formatValueWithCount(
  value: unknown,
  name: unknown,
  item: { dataKey?: unknown; payload?: ChartRow }
): [string, string] {
  const numericValue = typeof value === "number" ? value : Number(value) || 0
  const dataKey = item.dataKey != null ? String(item.dataKey) : undefined
  const count = dataKey ? item.payload?.[countKeyFor(dataKey)] : undefined

  const formatted = formatNumber(numericValue)
  return [
    typeof count === "number" ? `${formatted} (${count} txns)` : formatted,
    String(name),
  ]
}
